logging:
	config: classpath:logback.xml
spring:
	servlet:
		multipart:
			enabled: true
 			file-size-threshold: 0 
			location:
			max-file-size: 1MB 
			max-request-size: 10MB 
			resolve-lazily: false
---
email: 
	host: smtp.sendgrid.net
        user: support@upraxis.com
	port: 2525
	password: US3R2m@!lSTuff
	enable:
		debug: false
		auth: true
		starttls: false 
	protocol: smtp
---
spring:
	mvc:
		static-path-pattern: /resources/static/**
	messages:
		basename: locale/messages
